#!/usr/bin/env bash
# scripts/configure.sh - 환경 탐색 및 동적 변수 생성 (기존 check-deps.sh 대체)
#
# OS(Mac/Linux/Windows), 패키지 매니저(brew, apt 등), Docker 환경을
# 동적으로 탐지하여 .cockpit-local/.cockpit-env 파일을 생성합니다.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# lib/common.sh 에는 tui 관련 함수가 없거나 다를 수 있어 스크립트 안에 tui_banner를 선언
source "$SCRIPT_DIR/lib/common.sh" 2>/dev/null || true
tui_banner() { printf '\n\033[1m\033[36m%s\033[0m\n' "$*"; }

detect_os_and_package_manager() {
  OS_TYPE="$(uname -s)"
  ARCH_TYPE="$(uname -m)"
  PKG_MANAGER=""
  DOCKER_CMD="docker"
  NEEDS_COLIMA="false"

  if [ "$OS_TYPE" = "Darwin" ]; then
    PKG_MANAGER="brew"
    if ! command -v docker >/dev/null 2>&1; then
      NEEDS_COLIMA="true"
    fi
  elif [ "$OS_TYPE" = "Linux" ]; then
    if command -v apt-get >/dev/null 2>&1; then
      PKG_MANAGER="apt-get"
    elif command -v yum >/dev/null 2>&1; then
      PKG_MANAGER="yum"
    fi
  elif [[ "$OS_TYPE" == *"MINGW"* ]] || [[ "$OS_TYPE" == *"CYGWIN"* ]]; then
    PKG_MANAGER="choco"
  fi

  printf "  \033[2m· OS: %s\033[0m\n" "$OS_TYPE"
  printf "  \033[2m· Arch: %s\033[0m\n" "$ARCH_TYPE"
  printf "  \033[2m· Package Manager: %s\033[0m\n" "${PKG_MANAGER:-Unknown}"
}

export_environment_variables() {
  local LOCAL_DIR="$ROOT_DIR/.cockpit-local"
  mkdir -p "$LOCAL_DIR"
  local ENV_FILE="$LOCAL_DIR/.cockpit-env"

  cat <<EOF > "$ENV_FILE"
# 🚀 Auto-generated by configure.sh (do not edit manually unless needed)
export OS_TYPE="$OS_TYPE"
export ARCH_TYPE="$ARCH_TYPE"
export PKG_MANAGER="$PKG_MANAGER"
export DOCKER_CMD="$DOCKER_CMD"
export NEEDS_COLIMA="$NEEDS_COLIMA"
EOF

  printf "  \033[32m✓\033[0m 환경 변수 생성 완료: %s\n\n" "$ENV_FILE"
}

check_req() {
  if ! command -v "$1" >/dev/null 2>&1; then
    MISSING_PKGS+=("$1")
  else
    printf "  \033[32m✓\033[0m 필수 도구 확인: %s\n" "$1"
  fi
}

install_missing_required_packages() {
  MISSING_PKGS=()
  printf "  \033[34m→\033[0m 필수 도구 검증\n"
  check_req "git"
  check_req "jq"
  check_req "curl"

  if [ ${#MISSING_PKGS[@]} -gt 0 ]; then
    if [ -n "$PKG_MANAGER" ]; then
      printf "  \033[33m⚠\033[0m 필수 패키지가 누락되었습니다: %s\n" "${MISSING_PKGS[*]}"
      printf "  \033[34m→\033[0m 자동 설치를 시도합니다 (%s)...\n" "$PKG_MANAGER"
      
      if [ "$PKG_MANAGER" = "brew" ]; then
        brew install "${MISSING_PKGS[@]}"
      elif [ "$PKG_MANAGER" = "apt-get" ]; then
        sudo apt-get update && sudo apt-get install -y "${MISSING_PKGS[@]}"
      elif [ "$PKG_MANAGER" = "yum" ]; then
        sudo yum install -y "${MISSING_PKGS[@]}"
      elif [ "$PKG_MANAGER" = "choco" ]; then
        choco install -y "${MISSING_PKGS[@]}"
      else
        printf "  \033[31m✗\033[0m 자동 설치를 지원하지 않는 패키지 매니저입니다: %s\n" "$PKG_MANAGER"
        exit 1
      fi
    else
      printf "  \033[31m✗\033[0m 필수 패키지가 없으며 패키지 매니저를 감지할 수 없습니다: %s\n" "${MISSING_PKGS[*]}"
      exit 1
    fi
  fi
}

install_colima_if_needed() {
  if [ "$NEEDS_COLIMA" = "true" ] && [ "$PKG_MANAGER" = "brew" ]; then
    printf "  \033[33m⚠\033[0m Docker 런타임(Colima)이 없습니다. 백그라운드 설치를 시도합니다...\n"
    brew install colima docker || true
  fi
}

check_rec() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf "  \033[33m○\033[0m %-12s \033[2m(권장) %s\033[0m\n" "$1" "$2"
  else
    local ver
    ver="$("$1" --version 2>/dev/null | head -1 | cut -c 1-40 || echo '')"
    printf "  \033[32m✓\033[0m %-12s \033[2m%s\033[0m\n" "$1" "$ver"
  fi
}

run_doctor_checks() {
  printf "\n  \033[34m→\033[0m 권장 도구 진단 (Doctor - 부족해도 설치는 계속됩니다)\n"
  check_rec gh "GitHub 작업 전반"
  check_rec rg "ripgrep (초고속 검색)"
  check_rec fd "fd (초고속 파일 찾기)"
  check_rec bat "bat (cat 대체)"
  check_rec yq "yaml 파서"
  check_rec tree "디렉토리 구조 보기"
  check_rec shfmt "쉘 포맷터"
  check_rec shellcheck "쉘 정적 분석"
  check_rec python3 "Python 3 런타임"
  check_rec uv "초고속 Python 패키지 매니저"
  check_rec go "Go 컴파일러"
  check_rec ruff "Python 린터"
  check_rec biome "JS/TS 포맷터"
}

main() {
  tui_banner "▸ Phase 1 · Configure (환경 진단 및 설정)"
  
  detect_os_and_package_manager
  export_environment_variables
  install_missing_required_packages
  install_colima_if_needed
  run_doctor_checks

  printf "\n  \033[32m✓\033[0m Configure 완료. 환경이 준비되었습니다.\n"
}

main "$@"
